# Generated by Django 3.2.4 on 2021-08-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderitem_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='create_at',
        ),
    ]
