# Generated by Django 3.2.4 on 2021-08-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210818_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
