# Generated by Django 3.2.4 on 2021-08-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='charge_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
