# Generated by Django 3.2.4 on 2021-08-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_payment_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
