# Generated by Django 3.2.4 on 2021-08-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_payment_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
    ]
