# Generated by Django 3.2.4 on 2021-08-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_delete_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
