# Generated by Django 3.2.4 on 2021-09-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_order_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
