# Generated by Django 3.2.4 on 2021-09-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20210901_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponUser',
        ),
    ]
