# Generated by Django 3.2.4 on 2021-09-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.shipping'),
        ),
    ]
