# Generated by Django 3.2.4 on 2021-09-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_orderitem_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
