# Generated by Django 3.2.4 on 2021-09-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_order_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal'), ('After', 'Payment on delivery')], max_length=10, null=True),
        ),
    ]
