# Generated by Django 3.2.4 on 2021-09-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_shop_followers'),
        ('order', '0031_auto_20210918_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shop'),
        ),
    ]
