# Generated by Django 3.2.4 on 2021-09-21 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_shop_followers'),
        ('order', '0033_alter_orderitem_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shop', to='product.shop'),
        ),
    ]
